// Bitmap sticker path — shared TS rasterizer (Phase 1, Android dev-verify).
//
// WHY: the new-board D520BT (fw V1.1.7) DOUBLES every ROM font glyph, so the TEXT
// path (TsplBuilder.java / Swift buildTsplSticker / tsplReference.ts) prints garbled
// on those units. Both boards print a TSPL BITMAP raster block CLEAN. So we render
// the WHOLE sticker to a 1-bit raster in TS and send it via BITMAP — clean on the
// new board, identical layout to the old TEXT sticker.
//
// ARCHITECTURE (parity by construction):
//   stickerDrawOps()          — the LAYOUT, mirrored op-for-op from the frozen
//                               tsplReference.ts. THE single source of positions.
//   emitTextTspl(ops)         — serializes ops back into the exact TEXT/BAR stream.
//                               TEST-ONLY: proves emitTextTspl == the frozen
//                               reference byte-for-byte (layout fidelity guard).
//   rasterizeToBitmapTspl()   — the PRODUCTION path: ops → 1-bit buffer (glyph
//                               blit) → ink-band crop → BITMAP blocks → TSPL.
//
// The frozen TEXT builders/goldens are NEVER imported or modified here; the layout
// is re-derived and pinned by the parity test.
//
// Glyphs come from committed 1-bit atlases (glyphAtlas.latin.ts + glyphAtlas.cjk.ts,
// generated by scripts/gen-glyph-atlas.mjs). Runtime never rasterizes a font →
// deterministic goldens. Cells match the printer's built-in font boxes:
//   font "2" 12x20 · "3" 16x24 · "4" 24x32 · CJK "TSS24" 24x24.

// ── Atlas shape (produced by the generator) ─────────────────────────────────
export interface GlyphFont { w: number; h: number; glyphs: { [cp: number]: string } } // base64 rows, MSB-first, ceil(w/8) B/row x h
export interface GlyphAtlas { [fontKey: string]: GlyphFont }

// TSPL BITMAP polarity. TSPL standard + the owner's probe photo (black bar at the
// 0x00 top half) => an INK dot is bit 0, white is bit 1. Single flip point.
export const INK_IS_ZERO = true;

// ── Pure helpers — mirrors of tsplReference.ts / TsplBuilder.java (parity-tested) ──
const CRLF = [0x0d, 0x0a];
function asciiBytes(s: string): number[] {
  const out: number[] = [];
  for (let i = 0; i < s.length; i++) { const c = s.charCodeAt(i); out.push(c <= 127 ? c : 0x3f); }
  return out;
}
function truncate(s: string, maxLen: number): string { return s.length > maxLen ? s.slice(0, maxLen) : s; }
function safe(s: string): string { return s.replace(/"/g, "'"); }
function hasNonAscii(s: string): boolean { for (let i = 0; i < s.length; i++) if (s.charCodeAt(i) > 127) return true; return false; }
function isStrippable(cp: number): boolean {
  return cp >= 0x1f000 || (cp >= 0x2600 && cp <= 0x27bf) || (cp >= 0xfe00 && cp <= 0xfe0f) || cp === 0x200d || cp === 0x20e3;
}
function javaTrim(s: string): string {
  let a = 0, b = s.length;
  while (a < b && s.charCodeAt(a) <= 0x20) a++;
  while (b > a && s.charCodeAt(b - 1) <= 0x20) b--;
  return s.slice(a, b);
}
function stripEmoji(s: string): string {
  if (!s) return "";
  let kept = "";
  for (const ch of s) if (!isStrippable(ch.codePointAt(0) ?? 0)) kept += ch;
  return javaTrim(kept);
}
function money(v: number): string { return v === Math.trunc(v) ? String(v) : v.toFixed(2); }
const SCRIPT_ASCII = 1, SCRIPT_CJK = 2, SCRIPT_UNSUPPORTED = 3;
const ATOMIC_LATIN: Record<string, string> = {
  "đ": "d", "Đ": "D", "ł": "l", "Ł": "L", "ø": "o", "Ø": "O", "æ": "ae", "Æ": "AE",
  "œ": "oe", "Œ": "OE", "ß": "ss", "þ": "th", "Þ": "Th", "ð": "d", "Ð": "D", "ı": "i",
};
function transliterateLatin(s: string): string {
  if (!s) return "";
  let out = "";
  for (const ch of s.normalize("NFD")) {
    const cp = ch.codePointAt(0) ?? 0;
    if (cp >= 0x300 && cp <= 0x36f) continue;
    out += ATOMIC_LATIN[ch] ?? ch;
  }
  return out;
}
function isCjkIdeograph(cp: number): boolean {
  return (cp >= 0x4e00 && cp <= 0x9fff) || (cp >= 0x3400 && cp <= 0x4dbf) || (cp >= 0xf900 && cp <= 0xfaff);
}
function classifyScript(s: string): number {
  let hasCjk = false;
  for (const ch of s) {
    const cp = ch.codePointAt(0) ?? 0;
    if (cp <= 127) continue;
    if (isCjkIdeograph(cp)) { hasCjk = true; continue; }
    return SCRIPT_UNSUPPORTED;
  }
  return hasCjk ? SCRIPT_CJK : SCRIPT_ASCII;
}
function stripUnrenderable(s: string): string {
  let out = "";
  for (const ch of s) { const cp = ch.codePointAt(0) ?? 0; if (cp <= 127 || isCjkIdeograph(cp)) out += ch; }
  return out;
}

// ── Per-size layout config — dup of tsplReference STICKER_LAYOUTS (parity-tested) ──
export interface SizeConfig {
  wDots: number; rightEdge: number; storeGap: number; buyerNumYMul: number; buyerNumGap: number;
  nameGap: number; usernameGap: number; sepGap: number; sepWidth: number;
  orderEntryGuard: number; orderLoopGuard: number; showTotal: boolean; totalY: number; totalAmountX: number;
  nameCjkXMul: number; nameCjkYMul: number; nameCjkGap: number;
}
export const STICKER_LAYOUTS: Record<string, SizeConfig> = {
  "100x60": { wDots: 800, rightEdge: 784, storeGap: 55, buyerNumYMul: 2, buyerNumGap: 110, nameGap: 58, usernameGap: 58, sepGap: 10, sepWidth: 520, orderEntryGuard: 390, orderLoopGuard: 400, showTotal: true, totalY: 445, totalAmountX: 410, nameCjkXMul: 2, nameCjkYMul: 2, nameCjkGap: 58 },
  "80x60":  { wDots: 640, rightEdge: 624, storeGap: 35, buyerNumYMul: 2, buyerNumGap: 95, nameGap: 40, usernameGap: 35, sepGap: 10, sepWidth: 360, orderEntryGuard: 350, orderLoopGuard: 360, showTotal: true, totalY: 395, totalAmountX: 250, nameCjkXMul: 2, nameCjkYMul: 2, nameCjkGap: 58 },
  "80x50":  { wDots: 640, rightEdge: 624, storeGap: 35, buyerNumYMul: 2, buyerNumGap: 95, nameGap: 40, usernameGap: 35, sepGap: 10, sepWidth: 360, orderEntryGuard: 270, orderLoopGuard: 280, showTotal: true, totalY: 315, totalAmountX: 250, nameCjkXMul: 2, nameCjkYMul: 2, nameCjkGap: 58 },
  "70x50":  { wDots: 560, rightEdge: 544, storeGap: 35, buyerNumYMul: 2, buyerNumGap: 95, nameGap: 40, usernameGap: 35, sepGap: 10, sepWidth: 280, orderEntryGuard: 270, orderLoopGuard: 280, showTotal: true, totalY: 315, totalAmountX: 170, nameCjkXMul: 2, nameCjkYMul: 2, nameCjkGap: 58 },
  "60x40":  { wDots: 480, rightEdge: 464, storeGap: 30, buyerNumYMul: 1, buyerNumGap: 46, nameGap: 34, usernameGap: 30, sepGap: 6,  sepWidth: 200, orderEntryGuard: 240, orderLoopGuard: 264, showTotal: false, totalY: 0, totalAmountX: 0, nameCjkXMul: 2, nameCjkYMul: 2, nameCjkGap: 58 },
};
function stickerConfig(wMm: number, hMm: number): SizeConfig {
  return STICKER_LAYOUTS[`${wMm}x${hMm}`] ?? STICKER_LAYOUTS["100x60"];
}

// ── Payload (subset of NativeStickerPayload) ────────────────────────────────
export interface RasterOrder { time?: string; item?: string }
export interface RasterBuyer { num?: number; bNum?: number; name?: string; handle?: string; totalSpent?: number; orders?: RasterOrder[] }
export interface RasterSettings {
  printStoreName?: boolean; printBuyerNumber?: boolean; printBuyerUsername?: boolean; printOrderItems?: boolean; printTotal?: boolean;
  printStoreScale?: number; printBuyerNumberScale?: number; printBuyerNameScale?: number; printUsernameScale?: number;
  printOrderScale?: number; printCommentScale?: number; printTotalScale?: number;
}
export interface RasterPayload { storeName?: string; sessionDate?: string; currency?: string; buyer?: RasterBuyer; settings?: RasterSettings | null }

// ── Draw ops — the shared layout output ─────────────────────────────────────
export type DrawOp =
  | { k: "bar"; x: number; y: number; w: number; h: number }
  | { k: "txt"; x: number; y: number; font: "2" | "3" | "4"; s: string; xm: number; ym: number }
  | { k: "cjk"; x: number; y: number; s: string; xm: number; ym: number };

export interface DrawResult { ops: DrawOp[]; wDots: number; hDots: number; wMm: number; hMm: number }

// Re-derivation of tsplReference.buildTsplStickerReference, emitting draw ops
// instead of bytes. MUST stay behaviorally identical — pinned by the parity test.
export function stickerDrawOps(payload: RasterPayload, labelWidthMm: number, labelHeightMm: number): DrawResult {
  const ops: DrawOp[] = [];
  const c = stickerConfig(labelWidthMm, labelHeightMm);

  const textSmart = (x: number, y: number, asciiFont: "2" | "3" | "4", rawContent: string, xm: number, ym: number, cjkXm: number, cjkYm: number) => {
    const content = stripUnrenderable(transliterateLatin(rawContent));
    if (!content) return;
    if (!hasNonAscii(content)) { ops.push({ k: "txt", x, y, font: asciiFont, s: content, xm, ym }); return; }
    const maxChars = Math.max(1, Math.floor((c.rightEdge - x) / (24 * cjkXm)));
    ops.push({ k: "cjk", x, y, s: truncate(content, maxChars), xm: cjkXm, ym: cjkYm });
  };

  const buyer = payload.buyer ?? {};
  const settings = payload.settings;
  const storeName = payload.storeName ?? "";
  const sessionDate = payload.sessionDate ?? "";
  const currency = payload.currency ?? "";
  const buyerNum = buyer.num ?? buyer.bNum ?? 0;
  const buyerName = buyer.name ?? "";
  const buyerHandle = buyer.handle ?? "";
  const totalSpent = buyer.totalSpent ?? 0;
  const orders = buyer.orders ?? [];

  const flag = (key: keyof RasterSettings) => (settings == null ? true : settings[key] !== false);
  const printStoreName = flag("printStoreName");
  const printBuyerNumber = flag("printBuyerNumber");
  const printBuyerUsername = flag("printBuyerUsername");
  const printOrderItems = flag("printOrderItems");
  const printTotal = flag("printTotal");

  const F2 = 24, F3 = 24, F4 = 32;
  const cmul = (m: number) => Math.max(1, Math.min(8, m));
  const lvl = (key: keyof RasterSettings) => {
    const v = settings == null ? 1 : (settings[key] as number | undefined) ?? 1;
    return Math.max(1, Math.min(8, Number(v) || 1));
  };
  const lvlStore = lvl("printStoreScale");
  const lvlBuyerNum = lvl("printBuyerNumberScale");
  const lvlName = lvl("printBuyerNameScale");
  const lvlUser = lvl("printUsernameScale");
  const lvlOrder = lvl("printOrderScale");
  const lvlComment = lvl("printCommentScale");
  const lvlTotal = lvl("printTotalScale");

  ops.push({ k: "txt", x: 16, y: 10, font: "3", s: "SellerFlowLive", xm: 1, ym: 1 });
  if (sessionDate) ops.push({ k: "txt", x: 290, y: 18, font: "2", s: safe(truncate(sessionDate, 12)), xm: 1, ym: 1 });
  ops.push({ k: "bar", x: 0, y: 48, w: c.wDots, h: 3 });

  const cleanStoreName = stripEmoji(storeName);
  const cleanBuyerName = stripEmoji(buyerName);
  const cleanBuyerHandle = stripEmoji(buyerHandle);

  let nameSource = cleanBuyerName;
  if (buyerName && !cleanBuyerName) nameSource = cleanBuyerHandle ? cleanBuyerHandle : `Buyer #${buyerNum}`;
  let nameOut = transliterateLatin(nameSource);
  let nameTier = classifyScript(nameOut);
  if (nameTier === SCRIPT_UNSUPPORTED) {
    const handleOut = transliterateLatin(cleanBuyerHandle);
    if (handleOut && classifyScript(handleOut) === SCRIPT_ASCII) { nameOut = handleOut; nameTier = SCRIPT_ASCII; }
    else nameOut = "";
  }

  let extra = 0;
  let y = 60;
  if (printStoreName && cleanStoreName) {
    const m = cmul(lvlStore);
    textSmart(16, y, "3", safe(truncate(cleanStoreName, 36)), m, m, m, m);
    const d = (m - 1) * F3; y += c.storeGap + d; extra += d;
  }
  if (printBuyerNumber) {
    const ym = cmul(c.buyerNumYMul * lvlBuyerNum);
    ops.push({ k: "txt", x: 16, y, font: "4", s: "Buyer", xm: 2, ym });
    ops.push({ k: "txt", x: 280, y, font: "4", s: String(buyerNum), xm: 2, ym });
    const d = (ym - c.buyerNumYMul) * F4; y += c.buyerNumGap + d; extra += d;
  }
  if (nameOut) {
    const cjkName = nameTier === SCRIPT_CJK;
    const asciiX = cmul(lvlName), asciiY = cmul(lvlName);
    const cjkX = cmul(c.nameCjkXMul * lvlName), cjkY = cmul(c.nameCjkYMul * lvlName);
    textSmart(16, y, "4", safe(truncate(nameOut, 30)), asciiX, asciiY, cjkX, cjkY);
    const usedY = cjkName ? cjkY : asciiY;
    const refBaseY = cjkName ? c.nameCjkYMul : 1;
    const d = (usedY - refBaseY) * F4;
    y += (cjkName ? c.nameCjkGap : c.nameGap) + d;
    extra += (cjkName ? c.nameCjkGap - c.nameGap : 0) + d;
  }
  if (printBuyerUsername && cleanBuyerHandle) {
    const m = cmul(lvlUser);
    textSmart(16, y, "3", "@" + safe(truncate(cleanBuyerHandle, 30)), m, m, m, m);
    const d = (m - 1) * F3; y += c.usernameGap + d; extra += d;
  }
  if (printOrderItems && orders.length > 0 && y < c.orderEntryGuard + extra) {
    ops.push({ k: "bar", x: 16, y, w: c.sepWidth, h: 2 });
    y += c.sepGap;
    const maxOrders = 2;
    for (let i = 0; i < Math.min(orders.length, maxOrders) && y < c.orderLoopGuard + extra; i++) {
      const order = orders[i] ?? {};
      const time = order.time ?? "";
      const item = order.item ?? "";
      const cleanItem = stripEmoji(item);
      const tm = cmul(lvlOrder);
      const pm = cmul(lvlComment);
      if (time) ops.push({ k: "txt", x: 16, y, font: "2", s: safe(truncate(time, 10)), xm: tm, ym: tm });
      if (cleanItem) {
        const priceX = time ? 16 + (truncate(time, 10).length + 2) * 12 * tm : 180;
        textSmart(priceX, y, "4", safe(truncate(cleanItem, 12)), 2, pm, 2, pm);
      }
      const d = Math.max((tm - 1) * F2, (pm - 1) * F4); y += 38 + d; extra += d;
    }
  }
  if (printTotal && totalSpent > 0 && c.showTotal) {
    const totalY = c.totalY + extra;
    const lm = cmul(lvlTotal);
    ops.push({ k: "txt", x: 16, y: totalY, font: "3", s: "Total:", xm: lm, ym: lm });
    const am = cmul(lvlTotal);
    const totalStr = safe(currency) + money(totalSpent);
    ops.push({ k: "txt", x: c.totalAmountX, y: totalY, font: "4", s: safe(truncate(totalStr, 18)), xm: 2, ym: am });
  }

  return { ops, wDots: c.wDots, hDots: labelHeightMm * 8, wMm: labelWidthMm, hMm: labelHeightMm };
}

// ── TEST-ONLY backend: ops → the exact TEXT/BAR TSPL stream (parity proof) ────
export type GbkEncoder = (s: string) => number[];
export function emitTextTspl(payload: RasterPayload, wMm: number, hMm: number, gbk: GbkEncoder): Uint8Array {
  const { ops } = stickerDrawOps(payload, wMm, hMm);
  const out: number[] = [];
  const line = (s: string) => { out.push(...asciiBytes(s), ...CRLF); };
  line(`SIZE ${wMm} mm, ${hMm} mm`);
  line("GAP 2 mm, 0");
  line("DIRECTION 1");
  line("REFERENCE 0,0");
  line("DENSITY 8");
  line("CLS");
  for (const op of ops) {
    if (op.k === "bar") line(`BAR ${op.x},${op.y},${op.w},${op.h}`);
    else if (op.k === "txt") line(`TEXT ${op.x},${op.y},"${op.font}",0,${op.xm},${op.ym},"${op.s}"`);
    else { out.push(...asciiBytes(`TEXT ${op.x},${op.y},"TSS24.BF2",0,${op.xm},${op.ym},"`)); out.push(...gbk(op.s)); out.push(...asciiBytes(`"`), ...CRLF); }
  }
  line("PRINT 1");
  return Uint8Array.from(out);
}

// ── 1-bit raster buffer ─────────────────────────────────────────────────────
class Bitmap {
  readonly w: number; readonly h: number; readonly rowBytes: number; readonly buf: Uint8Array;
  constructor(w: number, h: number) { this.w = w; this.h = h; this.rowBytes = (w + 7) >> 3; this.buf = new Uint8Array(this.rowBytes * h); }
  private set(x: number, y: number) { if (x < 0 || y < 0 || x >= this.w || y >= this.h) return; this.buf[y * this.rowBytes + (x >> 3)] |= 0x80 >> (x & 7); }
  private get1(x: number, y: number): boolean { return (this.buf[y * this.rowBytes + (x >> 3)] & (0x80 >> (x & 7))) !== 0; }
  fillRect(x: number, y: number, w: number, h: number) { for (let j = 0; j < h; j++) for (let i = 0; i < w; i++) this.set(x + i, y + j); }
  // Blit a glyph cell (packed 1-bit, bit1=ink) scaled by integer (xm,ym), nearest-neighbour.
  blit(cell: Uint8Array, cw: number, ch: number, dstX: number, dstY: number, xm: number, ym: number) {
    const crb = (cw + 7) >> 3;
    for (let sy = 0; sy < ch; sy++) for (let sx = 0; sx < cw; sx++) {
      if ((cell[sy * crb + (sx >> 3)] & (0x80 >> (sx & 7))) === 0) continue;
      const bx = dstX + sx * xm, by = dstY + sy * ym;
      for (let j = 0; j < ym; j++) for (let i = 0; i < xm; i++) this.set(bx + i, by + j);
    }
  }
  rowHasInk(y: number): boolean { const off = y * this.rowBytes; for (let b = 0; b < this.rowBytes; b++) if (this.buf[off + b]) return true; return false; }
  // [minX, maxX) ink extent across rows [y0,y1). Returns null if none.
  inkExtent(y0: number, y1: number): [number, number] | null {
    let lo = this.w, hi = -1;
    for (let y = y0; y < y1; y++) for (let x = 0; x < this.w; x++) if (this.get1(x, y)) { if (x < lo) lo = x; if (x > hi) hi = x; }
    return hi < 0 ? null : [lo, hi + 1];
  }
}

const b64ToBytes = (b64: string): Uint8Array => {
  const bin = typeof atob === "function" ? atob(b64) : Buffer.from(b64, "base64").toString("binary");
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i) & 0xff;
  return out;
};

export interface RasterAtlases { latin: GlyphAtlas; cjk?: GlyphAtlas }

function paint(bmp: Bitmap, ops: DrawOp[], atlases: RasterAtlases) {
  const latin = atlases.latin;
  const cjkFont = atlases.cjk?.cjk;
  for (const op of ops) {
    if (op.k === "bar") { bmp.fillRect(op.x, op.y, op.w, op.h); continue; }
    if (op.k === "txt") {
      const f = latin[op.font]; if (!f) continue;
      let penX = op.x;
      for (const ch of op.s) {
        const cp = ch.codePointAt(0) ?? 0;
        const g = f.glyphs[cp];
        if (g) bmp.blit(b64ToBytes(g), f.w, f.h, penX, op.y, op.xm, op.ym);
        penX += f.w * op.xm; // fixed advance (mono cell), even for a missing glyph
      }
      continue;
    }
    // cjk op — every char rendered from the 24-cell CJK atlas (incl. halfwidth ASCII)
    if (!cjkFont) continue; // no CJK atlas yet (generated on Mac) → nothing painted
    let penX = op.x;
    for (const ch of op.s) {
      const cp = ch.codePointAt(0) ?? 0;
      const g = cjkFont.glyphs[cp];
      if (g) bmp.blit(b64ToBytes(g), cjkFont.w, cjkFont.h, penX, op.y, op.xm, op.ym);
      penX += cjkFont.w * op.xm;
    }
  }
}

export interface BitmapTsplResult { bytes: Uint8Array; bands: number; inkBytes: number }

// Full uncropped 1-bit raster (bit 1 = ink) — exported so the band-crop lossless
// invariant test can recompose the emitted BITMAP blocks against it.
export interface FullRaster { buf: Uint8Array; w: number; h: number; rowBytes: number }
export function renderStickerBitmap(payload: RasterPayload, wMm: number, hMm: number, atlases: RasterAtlases): FullRaster {
  const { ops, wDots, hDots } = stickerDrawOps(payload, wMm, hMm);
  const bmp = new Bitmap(wDots, hDots);
  paint(bmp, ops, atlases);
  return { buf: bmp.buf, w: bmp.w, h: bmp.h, rowBytes: bmp.rowBytes };
}

// PRODUCTION path: payload → 1-bit raster → ink-band crop → BITMAP blocks → TSPL.
export function rasterizeToBitmapTspl(payload: RasterPayload, wMm: number, hMm: number, atlases: RasterAtlases): BitmapTsplResult {
  const { ops, wDots, hDots } = stickerDrawOps(payload, wMm, hMm);
  const bmp = new Bitmap(wDots, hDots);
  paint(bmp, ops, atlases);

  const out: number[] = [];
  const line = (s: string) => { out.push(...asciiBytes(s), ...CRLF); };
  line(`SIZE ${wMm} mm, ${hMm} mm`);
  line("GAP 2 mm, 0");
  line("DIRECTION 1");
  line("REFERENCE 0,0");
  line("DENSITY 8");
  line("CLS");

  // Ink-band cropping: maximal runs of inked rows → one BITMAP each, cropped to
  // the horizontal ink extent. Blank rows/columns are never transmitted.
  let bands = 0, inkBytes = 0;
  let y = 0;
  while (y < hDots) {
    if (!bmp.rowHasInk(y)) { y++; continue; }
    let y1 = y + 1;
    while (y1 < hDots && bmp.rowHasInk(y1)) y1++;
    const ext = bmp.inkExtent(y, y1);
    if (ext) {
      const [x0, x1] = ext;
      const bandW = x1 - x0, bandH = y1 - y;
      const rowBytes = (bandW + 7) >> 3;
      const data = new Uint8Array(rowBytes * bandH);
      // Default every bit to WHITE, then stamp ink dots per polarity.
      if (!INK_IS_ZERO) { /* ink=1: buffer already 0 (white); set ink bits below */ }
      else data.fill(0xff); // ink=0: start all-white(1), clear ink bits to 0
      for (let ry = 0; ry < bandH; ry++) for (let rx = 0; rx < bandW; rx++) {
        const ink = (bmp.buf[(y + ry) * bmp.rowBytes + ((x0 + rx) >> 3)] & (0x80 >> ((x0 + rx) & 7))) !== 0;
        if (!ink) continue;
        const idx = ry * rowBytes + (rx >> 3), mask = 0x80 >> (rx & 7);
        if (INK_IS_ZERO) data[idx] &= ~mask; else data[idx] |= mask;
      }
      out.push(...asciiBytes(`BITMAP ${x0},${y},${rowBytes},${bandH},0,`));
      for (let i = 0; i < data.length; i++) out.push(data[i]);
      out.push(...CRLF);
      bands++; inkBytes += data.length;
    }
    y = y1;
  }
  line("PRINT 1");
  return { bytes: Uint8Array.from(out), bands, inkBytes };
}

// Base64 for the native bridge (chunked, binary-safe — mirrors printProbe.toBase64).
export function bytesToBase64(bytes: Uint8Array): string {
  if (typeof btoa !== "function") return typeof Buffer !== "undefined" ? Buffer.from(bytes).toString("base64") : "";
  let bin = ""; const CH = 0x8000;
  for (let i = 0; i < bytes.length; i += CH) bin += String.fromCharCode.apply(null, Array.from(bytes.subarray(i, i + CH)));
  return btoa(bin);
}
